### PR TITLE
fix(xsai): xsai-tools-sent-undefined

### LINKED ISSUE #337: [BUG]XSAIError: "[] is too short - 'tools'" when using XSAIProvider with Alibaba Cloud Qwen models
### Describe the bug

When using XSAIProvider from @voltagent/xsai to connect to Alibaba Cloud's Qwen models, the following error occurs during agent text generation:
```
XSAIError: Remote sent 400 response: {"error":{"code":null,"param":null,"message":"[] is too short - 'tools'","type":"invalid_request_error"},"request_id":"chatcmpl-0b55910f-cbb5-91b3-b41c-66f49d90c473"}
```

### Steps To Reproduce

1. In your @voltagent/core setup, configure XSAIProvider with Alibaba Cloud DashScope credentials:
```
   const AliProvider = new XSAIProvider({
     apiKey: process.env.DASH_SCOPE_API_KEY,
     baseURL: https://dashscope.aliyuncs.com/compatible-mode/v1
   });
```
2. When using the @voltagent/core agent, call function generateText() with qwen-turbo-latest model:
```
   const agent = new Agent({
     name: "my-agent", 
     instructions: "A helpful assistant that answers questions",
     llm: AliProvider,
     model: "qwen-turbo-latest",
   });
```
3. Send the following request to the API endpoint:
```
   const response = await agent.generateText("What is the capital of Canada?");
```
4. Observe the error log or incorrect response (e.g., in Supabase logs if using @voltagent/supabase):
```
   XSAIError: Remote sent 400 response: {"error":{"code":null,"param":null,"message":"[] is too short - 'tools'","type":"invalid_request_error"},"request_id":"chatcmpl-0b55910f-cbb5-91b3-b41c-66f49d90c473"}
```

### Expected behavior

success response

### Packages

"@voltagent/core": "^0.1.51",
"@voltagent/vercel-ai": "^0.1.13",
"@voltagent/xsai": "^0.2.3",
"xsai": "^0.3.0-beta.6",

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Adherentman**
fix #337 
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://voltagent.dev/docs/community/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://voltagent.dev/docs/community/contributing/#creating-a-changeset

## What is the new behavior?

fixes (issue)

### CODE REVIEW

File: packages/xsai/src/index.ts [hunk 1]
```diff
@@ -216,14 +216,14 @@ export class XSAIProvider implements LLMProvider<string> {
   ): Promise<ProviderTextResponse<GenerateTextResult>> => {
     const { generateText } = await import("xsai");
     const xsaiMessages = options.messages.map(this.toMessage);
-    const xsaiTools = (await this.convertTools(options.tools || [])) ?? [];
+    const xsaiTools = (await this.convertTools(options.tools || [])) ?? undefined;
```
Comment (kwaa) [inline packages/xsai/src/index.ts:219]:
```suggestion
    const xsaiTools = await this.convertTools(options.tools ?? []);
```

File: packages/xsai/src/index.ts [hunk 2]
```diff
@@ -216,14 +216,14 @@ export class XSAIProvider implements LLMProvider<string> {
...
 
     const result = await generateText({
       apiKey: this.apiKey,
       messages: xsaiMessages,
       model: options.model,
       tools: xsaiTools,
-      maxSteps: xsaiTools.length > 0 ? options.maxSteps : undefined,
+      maxSteps: xsaiTools && xsaiTools.length > 0 ? options.maxSteps : undefined,
```
Comment (kwaa) [inline packages/xsai/src/index.ts]:
```suggestion
      maxSteps: xsaiTools?.length > 0 ? options.maxSteps : undefined,
```

File: packages/xsai/src/index.ts (hunk 1 above)
Comment (kwaa) [inline packages/xsai/src/index.ts]: Since the empty array is already passed in `options.tools || []`, this should not work.

File: packages/xsai/src/index.ts (hunk 2 above)
Comment (Adherentman) [reply packages/xsai/src/index.ts:226]: will report 'xsaiTools.length' is possibly 'undefined'.

Comment (Adherentman) [reply packages/xsai/src/index.ts]: fix this

File: packages/xsai/src/index.ts (hunk 1 above)
Comment (Adherentman) [reply packages/xsai/src/index.ts]: fix this

File: .changeset/grumpy-bars-turn.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@voltagent/xsai": major
+---
+
+fix xsai empyt tools will sent undefined
```
Comment (omeraplak) [inline .changeset/grumpy-bars-turn.md]:
```suggestion
---
"@voltagent/xsai": patch
---

fix: xsai empty tools will sent undefined - #337
```

**Comment by omeraplak** [comment]
Thank you @Adherentman 🎯
